name: expensesAppTest
on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:7
        ports:
          - 27017:27017
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-node@v4
      with: {node-version: '20'}

    - name: Dependencies
      run: npm ci
      working-directory: ./frontend

    - name: Audit
      run: npm audit --audit-level=high
      working-directory: ./frontend

    - name: Dependencies1
      run: npm ci
      working-directory: ./backend

    - name: Audit1
      run: npm audit --audit-level=high
      working-directory: ./backend 

    - name: lint
      run: npm run lint
      working-directory: ./frontend

    - name: typeCheck
      run: npx tsc --noEmit
      working-directory: ./frontend

    - name: typeCheck1
      run: npm run typecheck
      working-directory: ./backend

    - name: checks
      run: npm run build
      working-directory: ./frontend

    - name: display the path
      shell: bash
      run: echo $PATH

    - name: Prettier
      run: npm run format:check
      working-directory: ./frontend

    - name: Run backend
      run: npm run start & 
      working-directory: ./backend

    - name: Run frontend
      run: npm run dev -- --host &
      working-directory: ./frontend

    - name: Sleep
      run: sleep 10

    - name: Libraries
      run: npx playwright install --with-deps chromium
      working-directory: ./frontend
    
    - name: Curl
      run: curl --fail http://localhost:3003/get

    - name: E2E
      run: npx playwright test e2e.spec.ts 
      working-directory: ./frontend 

    

    
